<div class="title"><h1>Ustawienia strony</h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li><a href="<?=$this->baseUrl;?>/admin/ustawienia/"><span class="fa i-cog"></span>Główne ustawienia strony</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/ustawienia/social/"><span class="fa i-lista"></span>Portale społecznościowe</a></li>
			<li class="active"><a href="<?=$this->baseUrl;?>/admin/ustawienia/mapa/"><span class="fa i-map"></span>Kontakt i mapa</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/ustawienia/backup/"><span class="fa i-sql"></span>Kopia bazy</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/ustawienia/baner/"><span class="fa i-image"></span>Baner na start</a></li>
		</ul>
		<div class="widget">
		<div class="tab-content">
			<div id="map"></div>
			<form id="ustawienia" name="ustawienia" enctype="application/x-www-form-urlencoded" class="mainForm" action="" method="post">
				<div class="formRow">
					<label for="map_nazwa">Nazwa</label>
					<div class="formRight tip rowInfo" data-original-title="Nazwa punktu" data-placement="bottom-left"><input type="text" name="map_nazwa" id="map_nazwa" value="<?=$this->header->map_nazwa;?>" size="67" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="map_lat">Szerokość geograficzna</label>
					<div class="formRight tip rowInfo" data-original-title="Szerokość geograficzna punktu" data-placement="bottom-left"><input type="text" name="map_lat" id="map_lat" value="<?=$this->header->map_lat;?>" size="67" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="map_lng">Szerokość geograficzna</label>
					<div class="formRight tip rowInfo" data-original-title="Szerokość geograficzna punktu" data-placement="bottom-left"><input type="text" name="map_lng" id="map_lng" value="<?=$this->header->map_lng;?>" size="67" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="map_zoom">Zbliżenie</label>
					<div class="formRight tip rowInfo" data-original-title="Przybliżenie mapy do punktu" data-placement="bottom-left"><input type="text" name="map_zoom" id="map_zoom" value="<?=$this->header->map_lng;?>" size="67" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="map_adress">Adres</label>
					<div class="formRight tip rowInfo" data-original-title="Przybliżenie mapy do punktu" data-placement="bottom-left"><input type="text" name="map_adress" id="addresspicker_map" value="<?=$this->header->map_adress;?>" size="67" class="validate[required]" /></div>
				</div>
				<div class="formRow">
					<label for="map_link">Link do mapy</label>
					<div class="formRight tip rowInfo" data-original-title="Link do Google Maps" data-placement="bottom-left"><input type="text" name="map_link" id="map_link" value="<?=$this->header->map_link;?>" size="67" class="validate[required]" /></div>
				</div>

			<h2 class="section">Godziny pracy</h2>
				<div class="formRow">
					<label for="godz_pon">Poniedziałek</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_pon" id="godz_pon" value="<?=$this->header->godz_pon;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_wt">Wtorek</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_wt" id="godz_wt" value="<?=$this->header->godz_wt;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_srd">Środa</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_srd" id="godz_srd" value="<?=$this->header->godz_srd;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_czw">Czwartek</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_czw" id="godz_czw" value="<?=$this->header->godz_czw;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_pt">Piątek</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_pt" id="godz_pt" value="<?=$this->header->godz_pt;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_sb">Sobota</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_sb" id="godz_sb" value="<?=$this->header->godz_sb;?>" size="67"/></div>
				</div>
				<div class="formRow">
					<label for="godz_nd">Niedziela</label>
					<div class="formRight tip rowInfo"><input type="text" name="godz_nd" id="godz_nd" value="<?=$this->header->godz_nd;?>" size="67"/></div>
				</div>
				
				
		
				<div class="formSubmit"><input type="submit" name="submitUstawienia" id="submit" value="Zapisz" class="greyishBtn" /></div>
			</form>
		</div>
		</div>
	</div>
</div>
<script src="http://maps.google.com/maps/api/js?key=<?=$this->header->googlemapapi;?>"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/i18n/jquery-ui-i18n.min.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl; ?>/public/js/addresspicker.js" charset="utf-8"></script>
<script>
$(function() {
var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
  regionBias: "pl",
  componentsFilter: 'country:PL',
  updateCallback: showCallback,
  mapOptions: {
	<?php if($this->header->map_zoom) {?>zoom: <?=$this->header->map_zoom;?>,<?php } else { ?>zoom: 15,<?php } ?>
	center: new google.maps.LatLng(51.758670, 19.456560),
	scrollwheel: false,
	mapTypeId: google.maps.MapTypeId.ROADMAP
  },
  elements: {
	map:      "#map",
	lat:      "#map_lat",
	lng:      "#map_lng",
  }
});

var gmarker = addresspickerMap.addresspicker( "marker");
gmarker.setVisible(true);
addresspickerMap.addresspicker( "updatePosition");

function showCallback(geocodeResult, parsedGeocodeResult){
  $('#callback_result').text(JSON.stringify(parsedGeocodeResult, null, 4));
}
var map = $("#addresspicker_map").addresspicker("map");
google.maps.event.addListener(map, 'idle', function(){
	$('#map_zoom').val(map.getZoom());
});

});
</script>