<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/"><span class="fa i-stat"></span>Statystyki</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/formularze/"><span class="fa i-stat"></span>Statystyki formularzy</a></li></li>
			<li class="active"><a href="<?=$this->baseUrl;?>/admin/statystyki/mieszkania/"><span class="fa i-stat"></span>Statystyki mieszkań</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/kontakt/"><span class="fa i-lista"></span>Formularz kontaktowy</a></li>
		</ul>
		<div class="widget">
			<div class="table-header">
				<form action="" id="date-form" method="get">
					<label><span>Data początkowa:</span><input type="text" size="30" maxlength="30" id="data_start" name="data_start" value="<?=$this->data_start;?>" /></label>
					<label><span>Data końcowa:</span><input type="text" size="30" maxlength="30" id="data_end" name="data_end" value="<?=$this->data_end;?>" /></label>
					<label>
						<select name="id_inwest">
							<option value="">Wszystkie</option>
							<?php foreach($this->inwestlista as $inwest){?>
							<option value="<?=$inwest->id;?>"<?php if($this->etap == $inwest->id){?> selected<?php } ?>><?=$inwest->nazwa;?></option>
							<?php } ?>
						</select>
					</label>
					<label><input type="submit" class="greyishBtn" value="Pokaz"></label>
				<div class="clr"></div>
				</form>
			</div>
			<div class="col-2">
				<div class="panel-heading">
					<h6 class="panel-title">Najczęściej odwiedzane</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->mieszkania as $mieszkanie){?>
					<li><?=$mieszkanie->mieszkanie;?> (<?=$mieszkanie->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
			<div class="col-2">
				<div class="panel-heading">
					<h6 class="panel-title">Najrzadziej odwiedzane</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->mieszkania2 as $mieszkanie){?>
					<li><?=$mieszkanie->mieszkanie;?> (<?=$mieszkanie->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
		</div>
	</div>
</div>