<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/"><span class="fa i-stat"></span>Statystyki</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/formularze/"><span class="fa i-stat"></span>Statystyki formularzy</a></li></li>
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/mieszkania/"><span class="fa i-stat"></span>Statystyki mieszkań</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/statystyki/kontakt/"><span class="fa i-lista"></span>Formularz kontaktowy</a></li>
			<li class="active"><a href="<?=$this->baseUrl;?>/admin/statystyki/wyszukiwanie/"><span class="fa i-szukaj"></span>Wyszukiwarka</a></li>
		</ul>
		<div class="widget">
			<div class="table-header">
				<form action="" id="date-form" method="get">
					<label><span>Data początkowa:</span><input type="text" size="30" maxlength="30" id="data_start" name="data_start" value="<?=$this->data_start;?>" /></label>
					<label><span>Data końcowa:</span><input type="text" size="30" maxlength="30" id="data_end" name="data_end" value="<?=$this->data_end;?>" /></label>
					<label>
						<select name="id_inwest">
							<option value="">Wszystkie</option>
							<?php foreach($this->inwestlista as $inwest){?>
							<option value="<?=$inwest->id;?>"<?php if($this->etap == $inwest->id){?> selected<?php } ?>><?=$inwest->nazwa;?></option>
							<?php } ?>
						</select>
					</label>
					<label><input type="submit" class="greyishBtn" value="Pokaz"></label>
				<div class="clr"></div>
				</form>
			</div>
			<div class="col-3">
				<div class="panel-heading">
					<h6 class="panel-title">Liczba pokoi</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->pokoje as $pokoje){?>
					<li><?php if($pokoje->pokoje == 0) {echo 'brak wyboru';} else { echo $pokoje->pokoje; };?> (<?=$pokoje->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
			<div class="col-3">
				<div class="panel-heading">
					<h6 class="panel-title">Piętro</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->pietro as $pietro){?>
					<li><?php
					if($pietro->pietro == 99) {echo 'parter';} else { echo $pietro->pietro; }?> (<?=$pietro->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
			<div class="col-3">
				<div class="panel-heading">
					<h6 class="panel-title">Kuchnia/aneks</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->kuchnia_aneks as $kuchnia_aneks){?>
					<li><?php
					if($kuchnia_aneks->kuchnia_aneks == 0) {echo 'brak wyboru';}
					if($kuchnia_aneks->kuchnia_aneks == 1) {echo 'osobna kuchnia';}
					if($kuchnia_aneks->kuchnia_aneks == 2) {echo 'aneks kuchenny';}
					;?> (<?=$kuchnia_aneks->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
			<div class="clr"></div>
			<div class="col-1">
				<div class="panel-heading">
					<h6 class="panel-title">Powierzchnia</h6>
				</div>
				<div class="panel-body">
				<ol>
<? foreach($this->pow as $pow){?>
					<li><?=$pow->pow_od;?> - <?=$pow->pod_do;?> (<?=$pow->num;?>)</li>
<?php } ?>
				</ol>
				</div>
			</div>
		</div>
	</div>
</div>