<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav-tabs none">
			<li class="active"><a href="<?=$this->baseUrl;?>/admin/slider/"><span class="fa i-image"></span>Obrazki slidera</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/slider/ustawienia/"><span class="fa i-cog"></span>Ustawienia</a></li></li>
		</ul>
		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="50%">Tytuł</th>
					<th width="40%">Miniaturka</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
				<td><?=$this->escape($pozycja->tytul);?></td>
				<td><img src="<?=$this->baseUrl;?>/files/slider/thumbs/<?=$this->escape($pozycja->plik);?>" alt=""></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/slider/edytuj/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/slider/usun/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/slider/nowy/" class="button greyishBtn">Dodaj panel</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$("#sortable tbody.content").sortuj('<?=$this->baseUrl;?>/admin/slider/ustaw/');
});
//]]>
</script>