<div class="container">
<?php foreach($this->news as $key => $post){?>
	<div class="col-12 entry-post">
		<div class="entry-shadow">
			<article id="post-" itemscope itemType="http://schema.org/BlogPosting">
				<div class="row no-gutters">
<?php if($key % 2 == 0) {?>
					<?php if($post->plik){?><div class="col-6 col-news-thumb"><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" itemprop="url"><img src="<?=$this->baseUrl;?>/files/news/thumbs/<?=$post->plik;?>" alt="<?=$post->tytul;?>"></a></div><?php } ?>
					<div class="<?php if($post->plik){?>col-6 col-news-entry<?php } else {?>col-12<?php } ?>">
						<div class="entry-shadow-content">
							<h2><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" title="<?=$post->tytul;?>" itemprop="url"><span itemprop="name headline"><?=$post->tytul;?></span></a></h2>
							<div class="entry-content" itemprop="description">
								<p><?=previewParser($post->wprowadzenie, 600);?> ...</p>
								<a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" title="<?=$post->tytul;?>" class="gradient hvr-ripple-out">czytaj więcej</a>
							</div>
						</div>
					</div>
<?php } else {?>
					<div class="<?php if($post->plik){?>col-6 col-news-entry<?php } else {?>col-12<?php } ?>">
						<div class="entry-shadow-content">
							<h2><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" title="<?=$post->tytul;?>" itemprop="url"><span itemprop="name headline"><?=$post->tytul;?></span></a></h2>
							<div class="entry-content" itemprop="description">
								<p><?=previewParser($post->wprowadzenie, 600);?> ...</p>
								<a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" title="<?=$post->tytul;?>" class="gradient hvr-ripple-out">czytaj więcej</a>
							</div>
						</div>
					</div>
					<?php if($post->plik){?><div class="col-6 col-news-thumb"><a href="<?=$this->baseUrl;?>/aktualnosci/<?=$post->tag;?>/" itemprop="url"><img src="<?=$this->baseUrl;?>/files/news/thumbs/<?=$post->plik;?>" alt="<?=$post->tytul;?>"></a></div><?php } ?>
<?php } ?>			
				</div>
			<meta itemprop="author" content="<?= $this->header->autor; ?>">
			<meta itemprop="datePublished" content="<?=$post->data;?>">
			</article>
		</div>
	</div>
<?php } ?>
	
	<div class="row">
		<div class="col-12">
			<?= $this->paginationControl($this->news, 'Sliding', 'pagination.phtml'); ?>
		</div>
	</div>
</div>