<div id="dziennik">
	<div class="fluid-container">
		<div class="row">
			<div class="col-3 inwestmenu">
				<?php echo $this->render('inwestycja/aside.phtml');?>
			</div>
			
			<div class="col-9 inwestdesc">
				<div class="row">
					<div class="col-12 single-post">
						<?php if($this->news->plik){?><img src="<?=$this->baseUrl; ?>/files/inwestycje/news/<?=$this->news->plik;?>" alt="<?=$this->news->tytul;?>" class="mb-4"><?php } ?>
						<div class="post-date small">
							<?php $dateArray=explode('-',$this->news->data); ?>
							<span class="month"><?= $dateArray[1];?>.<?= $dateArray[0];?></span>
						</div>
						<h1 class="source"><span itemprop="name headline"><?=$this->news->tytul;?></span></h1>
						
						<p><b><?=$this->news->wprowadzenie;?></b></p>
						<br>
						<?=replace($this->news->tekst); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>