<div id="dziennik">
	<div class="container">
		<div class="row">
			<div class="col-12"><h1 class="source"><?=$this->zrealizowana->nazwa;?></h1></div>
		</div>
		<div class="row">
			<div class="col-2">
				<div class="zrealizowana-list">
					<img src="<?=$this->baseUrl;?>/public/gfx/template/maincontact-dots.png">
					<ul class="list-unstyled">
						<li><i class="fa-icons fa-calendar"></i> <strong>ROK:</strong> <?=$this->zrealizowana->koniec_rok;?></li>
						<li><i class="fa-icons fa-rooms"></i> <strong>MIESZKANIA:</strong> <?=$this->zrealizowana->koniec_mieszkania;?></li>
						<li><i class="fa-icons fa-city"></i> <strong>MIASTO:</strong> <?=$this->zrealizowana->koniec_miasto;?></li>
					</ul>

				</div>
			</div>

			<div class="col-10 inwestdesc">
				<img src="<?=$this->baseUrl;?>/files/inwestycje/miniaturka/<?=$this->zrealizowana->miniaturka;?>" alt="<?=$this->zrealizowana->nazwa;?>" class="pb-4">
				<?=replace($this->zrealizowana->opis);?>
			</div>
		</div>
	</div>
</div>