<div id="jakkupic">
	<div class="container">
		<div class="row">
			<div class="col-6 col-kupic-img">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 1){
							$plik1 = $pozycja->plik;
							$tekst1 = $pozycja->tekst;
							$tytul1 = $pozycja->nazwa;
						}
					}
				?>
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik1;?>" alt="<?=$tytul1;?>">
			</div>
			<div class="col-6 col-kupic-text">
				<h2 class="source"><?=$tytul1;?></h2>
				<?=$tekst1;?>
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-text">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 2){
							$plik2 = $pozycja->plik;
							$tekst2 = $pozycja->tekst;
							$tytul2 = $pozycja->nazwa;
						}
					}
				?>
				<h2 class="source"><?=$tytul2;?></h2>
				<?=$tekst2;?>
			</div>
			<div class="col-6 col-kupic-img">
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik2;?>" alt="<?=$tytul2;?>">
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-img">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 3){
							$plik3 = $pozycja->plik;
							$tekst3 = $pozycja->tekst;
							$tytul3 = $pozycja->nazwa;
						}
					}
				?>
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik3;?>" alt="<?=$tytul3;?>">
			</div>
			<div class="col-6 col-kupic-text">
				<h2 class="source"><?=$tytul3;?></h2>
				<?=$tekst3;?>
			</div>
		</div>
	</div>

	<div class="paralax-search" style="background:#222 url('<?=$this->baseUrl;?>/files/upload/paralaxa.jpg') no-repeat top center;background-attachment:fixed">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h2 class="source">4. Wybierz mieszkanie</h2>
				</div>
			</div>
			
			<div id="mainsearch">
				<form method="get" action="<?=$this->baseUrl;?>/szukaj/" class="main-search">
					<div class="container">
						<div class="row">
							<div class="col-4 search_input search_input_floor pr-0 pl-0">
								<select class="selectpicker" name="s_pokoje">
									<option value="">ILOŚĆ POKOI</option>
									<?php $var = explode(';', $this->header->mieszkania_pokoje); ?>
									<?php foreach($var as $pozycja) {?>
									<option value="<?=$pozycja;?>"<?php if($this->pokoje == $pozycja){echo ' selected="selected"';};?>>Pokoje: <?=$pozycja;?></option>
									<?php } ?>
								</select>
							</div>
							<div class="col-4 search_input search_input_middle">
								<select class="selectpicker" name="s_inwest">
									<option value="">INWESTYCJA</option>
									<?php foreach($this->inwestycje as $pozycja){?>
									<option value="<?=$pozycja->id;?>"><?=$pozycja->nazwa;?></option>
									<?php } ?>
								</select>
							</div>
							<div class="col-4 search_input pr-0 pl-0">
								<button type="submit">Szukaj</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row">
			<div class="col-6 col-kupic-img">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 4){
							$plik4 = $pozycja->plik;
							$tekst4 = $pozycja->tekst;
							$tytul4 = $pozycja->nazwa;
						}
					}
				?>
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik4;?>" alt="<?=$tytul4;?>">
			</div>
			<div class="col-6 col-kupic-text">
				<h2 class="source"><?=$tytul4;?></h2>
				<?=$tekst4;?>
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-text">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 5){
							$plik5 = $pozycja->plik;
							$tekst5 = $pozycja->tekst;
							$tytul5 = $pozycja->nazwa;
						}
					}
				?>
				<h2 class="source"><?=$tytul5;?></h2>
				<?=$tekst5;?>
			</div>
			<div class="col-6 col-kupic-img">
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik5;?>" alt="<?=$tytul5;?>">
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-img">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 6){
							$plik6 = $pozycja->plik;
							$tekst6 = $pozycja->tekst;
							$tytul6 = $pozycja->nazwa;
						}
					}
				?>
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik6;?>" alt="<?=$tytul6;?>">
			</div>
			<div class="col-6 col-kupic-text">
				<h2 class="source"><?=$tytul6;?></h2>
				<?=$tekst6;?>
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-text">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 7){
							$plik7 = $pozycja->plik;
							$tekst7 = $pozycja->tekst;
							$tytul7 = $pozycja->nazwa;
						}
					}
				?>
				<h2 class="source"><?=$tytul7;?></h2>
				<?=$tekst7;?>
			</div>
			<div class="col-6 col-kupic-img">
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik7;?>" alt="<?=$tytul7;?>">
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-img">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 8){
							$plik8 = $pozycja->plik;
							$tekst8 = $pozycja->tekst;
							$tytul8 = $pozycja->nazwa;
						}
					}
				?>
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik8;?>" alt="<?=$tytul8;?>">
			</div>
			<div class="col-6 col-kupic-text">
				<h2 class="source"><?=$tytul8;?></h2>
				<?=$tekst8;?>
			</div>
		</div>
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-6 col-kupic-text">
				<?php
					foreach($this->lista as $pozycja){
						if($pozycja->id == 9){
							$plik9 = $pozycja->plik;
							$tekst9 = $pozycja->tekst;
							$tytul9 = $pozycja->nazwa;
						}
					}
				?>
				<h2 class="source"><?=$tytul9;?></h2>
				<?=$tekst9;?>
			</div>
			<div class="col-6 col-kupic-img">
				<img src="<?=$this->baseUrl;?>/files/minislider/<?=$plik9;?>" alt="<?=$tytul9;?>">
			</div>
		</div>
	</div>

</div>

<div id="maincontact">
	<div class="container">
		<div class="row">
			<div class="col-12"><hr></div>
		</div>
		<div class="row">
			<div class="col-12">
				<form method="post" action="<?=$this->baseUrl;?>/kontakt/" class="validateform">
					<div class="row">
						<div class="col-12">
							<h2 class="source after-title">Skontaktuj się z nami</h2>
							<p class="section-title after-h2">Z przyjemnością odpowiemy na wszystkie Twoje pytania</p>
						</div>
					</div>
					<div class="form-row row">
						<div class="col-3">
							<div class="inputs">
								<div class="input">
									<label for="form_imie">Imię</label>
									<input name="imie" id="form_imie" class="validate[required]" placeholder="Imię" type="text">
								</div>
								<div class="input">
									<label for="form_email">E-mail</label>
									<input name="email" id="form_email" class="validate[required,custom[email]]" placeholder="E-mail" type="email">
								</div>
								<div class="input">
									<label for="form_tel">Telefon</label>
									<input name="telefon" id="form_tel" class="validate[custom[phone]]" placeholder="Telefon" type="tel">
								</div>
							</div>
						</div>
						<div class="col-9">
							<div class="input">
								<label for="form_wiadomosc">Treść wiadmości</label>
								<textarea name="wiadomosc" id="form_wiadomosc" placeholder="Treść wiadomości"></textarea>
							</div>
						</div>
					</div>
					<div class="form-row row">
						<div class="col-12 obowiazek">
							<?=$this->rodo->obowiazek;?>
						</div>
					</div>
					<div class="form-row row">
						<div class="col-12 rules">
						<?php foreach($this->regulkis as $regulka){?>
							<label for="zgoda_<?=$regulka['id'];?>" class="rules-text"><input name="zgoda_<?=$regulka['id'];?>" id="zgoda_<?=$regulka['id'];?>" value="1" type="checkbox" <?php if($regulka['wymagane'] == 1){;?>class="validate[required]"<?php } ?> data-prompt-position="topLeft:0"><p><?=$regulka['tresc'];?></p></label>
							<div class="clr"></div>
						<?php } ?>
						</div>
					</div>
					<div class="form-row row">
						<div class="col-6 col-6-form-info">
							<ul class="formicons list-unstyled mb-0">
								<li class="formicons-address">
								<?php $form_dane_1 = explode("\n", $this->header->form_dane_1);
									foreach($form_dane_1 as $dane_1){
								?>
									<p><?=$dane_1;?></p>
								<?php } ?>
								</li>
								<li class="formicons-contact">
								<?php $form_dane_2 = explode("\n", $this->header->form_dane_2);
									foreach($form_dane_2 as $dane_2){
								?>
									<p><?=$dane_2;?></p>
								<?php } ?>
								</li>
							</ul>
						</div>
						<div class="col-6 col-6-form-submit">
							<div class="input text-right">
								<script>
								grecaptcha.ready(function() {
								grecaptcha.execute('6Les5X4UAAAAAGlmoPYctz-bWQJnefjDOIp9t9e2', {action: 'jakkupic'})
									.then(function(token) {
									console.log(token)
									document.getElementById('g-recaptcha-response').value = token;
									});
								});
								</script>
								<input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response">
								<script type="text/javascript">
									document.write("<button class=\"bttn bttn-send\" type=\"submit\">WYŚLIJ</button>");
								</script>
								<noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>