	<div class="col-12 text-center error-page">
        <h3>Strona, której szukasz nie została znaleziona (Błąd 404)!</h3>
        <p>Możliwe są trzy przyczyny:</p>
        <ul class="list-unstyled">
            <li>1. strona nie istnieje (została usunięta lub nigdy nie istniała),</li>
            <li>2. strona zmieniła swoje położenie ze względu na duże zmiany w serwisie,</li>
            <li>3. strona jest aktualnie w trakcie tworzenia ze względu na trwające w serwisie prace. </li>
        </ul>
		<a href="<?=$this->baseUrl;?>/" class="bttn bttn-more">Strona główna</a>
	</div>