<div class="title"><h1><?= $this->controlname; ?> - <?=$this->inwestycja->nazwa;?> - <?= $this->pagename; ?></h1></div>

<div class="row-fluid">
	<div class="span12">
		<div class="widget">
		<div class="tab-content">
			<?=$this->back ;?>
			<?=$this->info ;?>
			<?=$this->thumb ;?>
	<div class="mappa">
		<div class="mappa-tool">
			<div class="mappa-workspace">
				<div id="overflow" style="overflow:auto;width:100%;">
				<canvas class="mappa-canvas"></canvas>
				</div>
				<div class="mappa-toolbars">
					<ul class="mappa-drawers none">
						<li><input type="radio" name="tool" value="polygon" id="new" class="addPoint input_hidden"/><label for="new" class="actionBtn tip addPoint" title="Dodaj punkt">Dodaj punkt</label></li>
					</ul>
					<ul class="mappa-points none">
						<li><input checked="checked" type="radio" name="tool" id="move" value="arrow" class="movePoint input_hidden"/><label for="move" class="actionBtn tip movePoint" title="Przesuń punkt">Przesuń / Zaznacz</label></li>
						<li><input type="radio" name="tool" value="delete" id="delete" class="deletePoint input_hidden"/><label for="delete" class="actionBtn tip deletePoint" title="Usuń punkt">Usuń punkt</label></li>
					</ul>
					<ul class="mappa-list none"></ul>
					<ul class="mappa-points none">
						<li><a href="#" id="toggleparam" class="actionBtn tip toggleParam">Pokaż / ukryj parametry</a></li>
					</ul>
				</div>
			</div>
		</div>
<script src="<?=$this->baseUrl;?>/public/js/plan/underscore.js"></script>
<script src="<?=$this->baseUrl;?>/public/js/plan/backbone.js"></script>
<script src="<?=$this->baseUrl;?>/public/js/plan/backbone-relational.js"></script>
<script type="text/javascript">
	var map = {
		"name":"imagemap",
		"areas":[
			<?=$this->pietro->cords;?>
		]};
				
				
</script>
<script src="<?=$this->baseUrl;?>/public/js/plan/mappa-backbone.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		mapview = new MapView({el:'.mappa'}, map);
		mapview.loadImage('<?=$this->baseUrl;?>/files/inwestycje/plan/<?=$this->plan->plik;?>');
	});
</script>
	<?php echo $this->form ;?>
	</div>
		</div>
		</div>
	</div>
</div>