<div class="title"><h1><?= $this->controlname; ?><?= $this->pagename; ?></h1></div>

<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<div class="tab-content">
				<?=$this->back ;?>
				<?=$this->info ;?>
				<?=$this->thumb ;?>
				<div id="map"></div>
				<?=$this->form ;?>
			</div>
		</div>
	</div>
</div>
<script src="http://maps.google.com/maps/api/js?key=<?=$this->header->googlemapapi;?>"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/i18n/jquery-ui-i18n.min.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl; ?>/public/js/addresspicker.js" charset="utf-8"></script>
<script>
$(function() {
var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
  regionBias: "pl",
  componentsFilter: 'country:PL',
  updateCallback: showCallback,
  mapOptions: {
	<?php if($this->mapa->zoom) {?>zoom: <?=$this->mapa->zoom;?>,<?php } else { ?>zoom: 15,<?php } ?>
	center: new google.maps.LatLng(51.107707, 17.038651),
	scrollwheel: false,
	mapTypeId: google.maps.MapTypeId.ROADMAP
  },
  elements: {
	map:      "#map",
	lat:      "#lat",
	lng:      "#lng",
  }
});

var gmarker = addresspickerMap.addresspicker( "marker");
gmarker.setVisible(true);
addresspickerMap.addresspicker( "updatePosition");

function showCallback(geocodeResult, parsedGeocodeResult){
  $('#callback_result').text(JSON.stringify(parsedGeocodeResult, null, 4));
}
var map = $("#addresspicker_map").addresspicker("map");
google.maps.event.addListener(map, 'idle', function(){
	$('#zoom').val(map.getZoom());
});

});
</script>
<?php if($this->tinymce) :?>
<script type="text/javascript">
$(document).ready(function() { 
	tinymce();
tinymce.create('tinymce.plugins.kCMSPlugin', {
    createControl: function(n, cm) {
        switch (n) {
			case 'galleryList':
                var glb = cm.createListBox('galerie', {
                     title : 'Wybierz galerię',
                     onselect : function(v) {
                         tinymce.activeEditor.execCommand('mceInsertContent', false, '<p>[galeria=galeria]'+ v +'[/galeria]</p>');
                     }
                });

                <?php 
				$db = Zend_Registry::get('db');
				$galeria = $db->fetchAll($db->select()->from('galeria')->order('nazwa ASC'));
				foreach($galeria as $galeria) { 
				?>
                glb.add('<?=$galeria->nazwa;?>', '<?=$galeria->id;?>');
				<?php } ?>
                return glb;
				
			case 'sliderList':
                var slb = cm.createListBox('slider', {
                     title : 'Wybierz slider',
                     onselect : function(v) {
                         tinymce.activeEditor.execCommand('mceInsertContent', false, '<p>[galeria=slider]'+ v +'[/galeria]</p>');
                     }
                });

                <?php 
				$db = Zend_Registry::get('db');
				$galeria = $db->fetchAll($db->select()->from('galeria')->order('nazwa ASC'));
				foreach($galeria as $galeria) { 
				?>
                slb.add('<?=$galeria->nazwa;?>', '<?=$galeria->id;?>');
				<?php } ?>
                return slb;
				
			case 'karuzelaList':
                var klb = cm.createListBox('karuzela', {
                     title : 'Wybierz karuzele',
                     onselect : function(v) {
                         tinymce.activeEditor.execCommand('mceInsertContent', false, '<p>[galeria=karuzela]'+ v +'[/galeria]</p>');
                     }
                });

                <?php 
				$db = Zend_Registry::get('db');
				$galeria = $db->fetchAll($db->select()->from('galeria')->order('nazwa ASC'));
				foreach($galeria as $galeria) { 
				?>
                klb.add('<?=$galeria->nazwa;?>', '<?=$galeria->id;?>');
				<?php } ?>
                return klb
				
			case 'mapList':
                var mlb = cm.createListBox('mapy', {
                     title : 'Wybierz lokalizacje',
                     onselect : function(v) {
                         tinymce.activeEditor.execCommand('mceInsertContent', false, '<p>[mapa]'+ v +'[/mapa]</p>');
                     }
                });
        }

        return null;
    }
});
	tinymce.PluginManager.add('kcmsplugin', tinymce.plugins.kCMSPlugin);
});</script>
<?php endif; ?>