<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="60%">Nazwa</th>
					<th width="30%">Miniaturka</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
				<td><?=$this->escape($pozycja->nazwa);?></td>
				<td><img src="<?=$this->baseUrl;?>/files/minislider/<?=$this->escape($pozycja->plik);?>" style="width:200px" alt=""></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/minislider/edytuj/id/<?=$this->escape($pozycja->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>