<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/lokalizacja/id/<?=$this->inwestycja->id;?>/"><span class="fa i-map"></span>Lokalizacja</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="75%">Nazwa</th>
					<th width="15%" class="center">Ikonka</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?= $this->escape($pozycja->id);?>">
				<td><?=$this->escape($pozycja->nazwa);?></td>
				<td class="center" style="background:#f9b22f"><img src="<?=$this->baseUrl;?>/files/inwestycje/atuty/<?=$pozycja->ikona;?>" style="width:50px" alt=""></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-atut/id/<?=$this->escape($pozycja->id);?>/inwest/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-atut/id/<?=$this->escape($pozycja->id);?>/inwest/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/nowy-atut/inwest/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj atut</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl;?>/admin/inwestycje/ustaw/co/inwestycje_atut/');
});
//]]>
</script>