<div class="title"><h1><?=$this->controlname;?> - Obrazek nagłówka: <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<ul class="nav nav-tabs none">
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
				<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-top/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Nagłówek inwestycji</a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
				<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
			</ul>
			
			<div class="table-header" style="padding:5px">
				<div class="info">Górny obrazek inwestycji 1920px szerokości / 400px wysokości</div>
				<div id="budynek">
					<img src="<?=$this->baseUrl;?>/files/inwestycje/top/<?=$this->inwestycja->top;?>" style="max-width:100%;height:auto" alt="">
				</div>
			</div>
			
			<div class="table-footer">
				<div id="jquery-wrapped-fine-uploader"></div>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl; ?>/public/js/fineuploader.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	var fileCount = 0;
	$('#jquery-wrapped-fine-uploader').fineUploader({
		debug: true,
		text: {
			uploadButton:'<div>Zmień obrazek inwestycji</div>'
		},
		request: {
			endpoint: '<?php echo $this->baseUrl; ?>/admin/inwestycje/top/id/<?=$this->inwestycja->id;?>/'
		}
	}).on('error', function(event, id, name, reason) {
	  })
	  .on('submit', function(id, nameN){
		fileCount++;
	  })
	  .on('complete', function(event, id, name, response){
			if(response.success==true){
				fileCount--;
				if(fileCount == 0){
					location.reload();
				}
			}
	  });

});
//]]>
</script>