<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav-tabs none">
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/wyszukiwarka/"><span class="fa i-szukaj"></span>Wyszukiwarka</a></li>
	</ul>
		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="5%" style="text-align:center">ID</th>
					<th width="40%">Nazwa</th>
					<th width="20%">Status</th>
					<th width="15%">Typ</th>
					<th width="10%">Data utworzenia</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?= $this->escape($lista->id);?>">
					<td class="center"><?=$this->escape($lista->id);?></td>
					<td><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->escape($lista->id);?>/"><?=$this->escape($lista->nazwa);?></a></td>
					<td><span class="inweststat-<?=$lista->status;?> typ-<?=$lista->typ;?>"><?=statusInwestycji($lista->status);?></span></td>
					<td><?=typ($lista->typ);?></td>
					<td><?=$this->escape($lista->data);?></td>
					<td class="right">
					<?php if($lista->typ <> 4){?>
					<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->escape($lista->id);?>/" class="actionBtn tip btnImage" title="Pokaż plan inwestycji"></a><?php } ?>
					<!--<a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->escape($lista->id);?>/" class="actionBtn tip btnPage" title="Pokaż strony"></a>-->
					<?php if($lista->typ <> 4){?><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->escape($lista->id);?>/" class="actionBtn tip btnCatalog" title="Pokaż inwestycję"></a><?php } ?> <a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-inwestycje/id/<?=$this->escape($lista->id);?>/" class="actionBtn tip btnEdit" title="Edytuj"></a>
					<a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-inwestycje/id/<?=$this->escape($lista->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
					</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php if($this->user->role == "admin") { ?><div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/nowa-inwestycja/" class="button greyishBtn">Dodaj inwestycję</a>
			</div>
			<?php } ?>
		</div>
	</div>
</div>
<?php if($this->user->role == "admin") { ?>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl;?>/admin/inwestycje/ustaw/co/inwestycje/');
});
//]]>
</script>
<?php } ?>