<div class="title"><h1><?=$this->controlname;?> - Lokalizacja: <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<ul class="nav nav-tabs none">
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
			<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/lokalizacja/id/<?=$this->inwestycja->id;?>/"><span class="fa i-map"></span>Lokalizacja</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
			<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
		</ul>

		<div class="widget" style="margin-top:1px">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="60%">Nazwa</th>
					<th width="30%">Adres</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $pozycja) : ?>
				<tr id="recordsArray_<?=$this->escape($pozycja->id);?>">
				<td><?=$this->escape($pozycja->nazwa);?></td>
				<td><?=$this->escape($pozycja->adres);?></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-punkt/id/<?=$this->escape($pozycja->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-punkt/id/<?=$this->escape($pozycja->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/nowy-punkt/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj wpis</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$("#sortable tbody.content").sortuj('<?php echo $this->baseUrl;?>/admin/inwestycje/ustaw-lokaliz/id/<?=$this->inwestycja->id;?>/');
});
//]]>
</script>