<div class="title"><h1><?=$this->controlname;?> - <?=$this->inwestycja->nazwa;?> - <?=$this->pietro->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
<?php if($this->inwestycja->typ == 1) {?>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-budynek/id/<?=$this->budynek->id;?>/inwestycja/<?=$this->inwestycja->id;?>/"><span class="fa i-lista"></span>Lista pięter: <?=$this->budynek->nazwa;?></a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/"><span class="fa i-lista"></span><?=$this->pietro->nazwa;?></a></li>
<?php } ?>

<?php if($this->inwestycja->typ == 2) {?>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/"><span class="fa i-lista"></span><?=$this->pietro->nazwa;?></a></li>
<?php } ?>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
						<th width="5%" style="text-align:center">Numer</th>
						<th width="55%">Nazwa</th>
						<th width="10%">Powierzchnia</th>
						<th width="20%">Status</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?=$this->escape($lista->id);?>">
				<td class="center"><?=$this->escape($lista->numer);?></td>
				<td><?=$this->escape($lista->nazwa);?></td>
				<td><?=$this->escape($lista->metry);?> m<sup>2</sup></td>
				<td><?=statusMieszkania($lista->status);?></td>
				<td class="right">
				<!--<a href="<?=$this->baseUrl;?>/admin/inwestycje/galeria-powierzchni/id/<?=$this->escape($lista->id);?>/pietro/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnImage" title="Pokaż galerię"></a>-->
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-powierzchnie/id/<?=$this->escape($lista->id);?>/typ/<?=$this->escape($lista->typ);?>/pietro/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnEdit" title="Edytuj"></a> 
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-powierzchnie/id/<?=$this->escape($lista->id);?>/pietro/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<?php if($this->pietro->typ == 1) {?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-powierzchnie/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>inwestycja/<?=$this->inwestycja->id;?>/pietro/<?=$this->pietro->id;?>/typ/1/" class="button greyishBtn">Dodaj mieszkanie</a>
				<?php } ?>
				
				<?php if($this->pietro->typ == 2) {?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-powierzchnie/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>inwestycja/<?=$this->inwestycja->id;?>/pietro/<?=$this->pietro->id;?>/typ/2/" class="button greyishBtn">Dodaj lokal usługowy</a>
				<?php } ?>
				
				<?php if($this->pietro->typ == 3) {?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-powierzchnie/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>inwestycja/<?=$this->inwestycja->id;?>/pietro/<?=$this->pietro->id;?>/typ/3/" class="button greyishBtn">Dodaj miejsce parkingowe</a>
				<?php } ?>
				
				<?php if($this->pietro->typ == 4) {?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-powierzchnie/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>inwestycja/<?=$this->inwestycja->id;?>/pietro/<?=$this->pietro->id;?>/typ/4/" class="button greyishBtn">Dodaj miejsce parkingowe</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl;?>/admin/inwestycje/ustaw/co/inwestycje_powierzchnia/');
});
//]]>
</script>