<div class="title"><h1><?=$this->controlname;?> - <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/lokalizacja/id/<?=$this->inwestycja->id;?>/"><span class="fa i-map"></span>Lokalizacja</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			
			<?php if($this->inwestycja->typ == 1){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="90%">Nazwa</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?=$this->escape($lista->id);?>">
				<td><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-budynek/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="tip" title="Pokaż budynek"><?=$this->escape($lista->nazwa);?></a></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-budynek/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż budynek"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-budynek/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-budynek/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$(".content").sortuj('<?=$this->baseUrl;?>/admin/inwestycje/ustaw/co/inwestycje_budynki/');
});
//]]>
</script>
			<?php } ?>
			
			<?php if($this->inwestycja->typ == 2){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="20%">Nazwa</th>
					<th width="70%">Numer</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr>
				<td><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="tip" title="Pokaż piętro"><?=$this->escape($lista->nazwa);?></a></td>
				<td><?=$this->escape($lista->numer);?></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż piętro"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/kopiuj-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnCopy" title="Kopiuj pietro"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php } ?>
			
			<?php if($this->inwestycja->typ == 3){?>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
						<th width="5%" style="text-align:center">Numer</th>
						<th width="55%">Nazwa</th>
						<th width="10%">Powierzchnia</th>
						<th width="20%">Status</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr id="recordsArray_<?=$this->escape($lista->id);?>">
				<td class="center"><?=$this->escape($lista->numer);?></td>
				<td><?=$this->escape($lista->nazwa);?></td>
				<td><?=$this->escape($lista->metry);?> m<sup>2</sup></td>
				<td><?=statusMieszkania($lista->status);?></td>
				<td class="right">
				<!--<a href="<?=$this->baseUrl;?>/admin/inwestycje/galeria-powierzchni/id/<?=$this->escape($lista->id);?>/pietro/<?=$this->pietro->id;?>/inwestycja/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1) {?>budynek/<?=$this->budynek->id;?>/<?php } ?>" class="actionBtn tip btnImage" title="Pokaż galerię"></a>-->
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-dom/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> 
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-dom/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php } ?>
			
			<div class="table-footer">
				<?php if($this->inwestycja->typ == 1){?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-budynek/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj budynek</a>
				<?php } ?>
				<?php if($this->inwestycja->typ == 2){?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-pietro/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj piętro</a>
				<?php } ?>
				<?php if($this->inwestycja->typ == 3){?>
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-dom/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj dom</a>
				<?php } ?>
			</div>
		</div>
	</div>
</div>