<div class="title"><h1><?=$this->controlname;?> - Przeglądasz: <?=$this->inwestycja->nazwa;?>: <?=$this->budynek->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-budynek/id/<?=$this->budynek->id;?>/inwestycja/<?=$this->inwestycja->id;?>/"><span class="fa i-lista"></span>Lista pięter: <?=$this->budynek->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="20%">Nazwa</th>
					<th width="70%">Numer</th>
					<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr>
				<td><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/" class="tip" title="Pokaż piętro"><?=$this->escape($lista->nazwa);?></a></td>
				<td><?=$this->escape($lista->numer);?></td>
				<td class="right">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/" class="actionBtn tip btnCatalog" title="Pokaż piętro"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/" class="actionBtn tip btnEdit" title="Edytuj"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a> <a href="<?=$this->baseUrl;?>/admin/inwestycje/kopiuj-pietro/id/<?=$this->escape($lista->id);?>/inwestycja/<?=$this->inwestycja->id;?>/budynek/<?=$this->budynek->id;?>/" class="actionBtn tip btnCopy" title="Kopiuj pietro"></a>
				</td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-pietro/budynek/<?=$this->budynek->id;?>/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj piętro</a>
			</div>
		</div>
	</div>
</div>