<div class="title"><h1><?=$this->controlname;?> - Przeglądasz: <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/lokalizacja/id/<?=$this->inwestycja->id;?>/"><span class="fa i-map"></span>Lokalizacja</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
	</ul>

		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="adm" id="sortable">
				<thead>
					<tr>
						<th width="5%">Pozycja</th>
						<th width="10%">Typ</th>
						<th width="70%">Nazwa</th>
						<th width="5%">Status</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
			<?php foreach($this->strony as $strony) : ?>
					<tr id="recordsArray_<?= $this->escape($strony->id);?>">
					<td class="center"><?= $this->escape($strony->sort);?></td>
					<td>
					<?php if($this->escape($strony->typ) == 0 ) { echo 'Strona'; }?>
					<?php if($this->escape($strony->typ) == 4 ) { echo 'Sekcja'; }?>
					</td>
					<td class="padleft"><?= $this->escape($strony->nazwa);?></td>
					<td class="padleft"><?= status($strony->status);?></td>
					<td class="center">
						<?php if($this->escape($strony->typ) == 0 ) {?>
						<a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-strone/id/<?= $this->escape($strony->id);?>/" class="actionBtn tip btnEdit"  title="Edytuj stronę"></a><?php } else { ?> <a href="<?=$this->baseUrl;?>/admin/inwestycje/edytuj-sekcje/id/<?= $this->escape($strony->id);?>/" class="actionBtn tip btnEdit"  title="Edytuj sekcje"></a><?php } ?> <a href="<?=$this->baseUrl;?>/admin/inwestycje/usun-strone/id/<?= $this->escape($strony->id);?>/" class="actionBtn tip btnDelete confirm" title="Usuń"></a>
					</td>
					</tr>
			<?php endforeach; ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/inwestycje/nowa-strona/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj stronę</a><!-- <a href="<?=$this->baseUrl;?>/admin/inwestycje/nowa-sekcja/inwestycja/<?=$this->inwestycja->id;?>/" class="button greyishBtn">Dodaj sekcję</a>-->
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$("#sortable tbody.content").sortuj('<?php echo $this->baseUrl;?>/admin/inwestycje/ustaw-strony/id/<?=$this->inwestycja->id;?>/');
});
//]]>
</script>