<div class="title"><h1><?=$this->controlname;?> - <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/szukaj-mieszkanie/id/<?=$this->inwestycja->id;?>/"><span class="fa i-szukaj"></span>Znajdź mieszkanie</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/strony/id/<?=$this->inwestycja->id;?>/"><span class="fa i-pages"></span>Strony</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/lokalizacja/id/<?=$this->inwestycja->id;?>/"><span class="fa i-map"></span>Lokalizacja</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/news/id/<?=$this->inwestycja->id;?>/"><span class="fa i-news"></span>Dziennik inwestycji</a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/atuty/id/<?=$this->inwestycja->id;?>/"><span class="fa i-atuty"></span>Atuty</a></li>
	</ul>

		<div class="widget">
			<div class="table-header znajdz">
				<form action="" method="get">
					<input type="text" name="numer" placeholder="Numer mieszkania" value="<?=$this->numer;?>">
					<input type="text" name="metraz_min" placeholder="Powierzchnia - od" value="<?=$this->areaFrom;?>">
					<input type="text" name="metraz_max" placeholder="Powierzchnia - do" value="<?=$this->areaTo;?>">
					<input type="text" name="pietro" placeholder="Pietro" value="<?=$this->floor;?>">
					<input type="text" name="pokoje" placeholder="Pokoje" value="<?=$this->rooms;?>">
					<select class="selectpicker" name="status">
						<option value="">Status</option>
						<option value="1"<?php if($this->status == 1){?> selected<?php } ?>>Na sprzedaż</option>
						<option value="2"<?php if($this->status == 2){?> selected<?php } ?>>Sprzedane</option>
						<option value="3"<?php if($this->status == 3){?> selected<?php } ?>>Rezerwacja</option>
					</select>
					<input type="submit" value="Szukaj">
				</form>
			</div>
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="35%">Nazwa</th>
					<th width="20%">Powierzchnia</th>
					<th width="20%">Piętro</th>
					<th width="20%">Status</th>
					<th width="5%"></th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->lista as $lista) : ?>
				<tr>
				<td><?=$lista->nazwa;?></td>
				<td><?=$lista->metry;?></td>
				<td><?=$lista->numer_pietro;?></td>
				<td><?=statusMieszkania($lista->status);?></td>
				<td><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz-pietro/id/<?=$lista->id_pietro;?>/inwestycja/<?=$this->inwestycja->id;?>/<?php if($this->inwestycja->typ == 1){?>budynek/<?=$lista->id_budynek;?>/<?php } ?>" class="actionBtn tip btnShow" title="Pokaż piętro" target="_blank"></a></td>
				</tr>
				<?php endforeach; ?>
				</tbody>
			</table>

		</div>
	</div>
</div>