<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/wyszukiwarka/"><span class="fa i-szukaj"></span>Wyszukiwarka</a></li>
	</ul>
		<div class="widget">
		<div class="tab-content">
			<form id="ustawienia" name="ustawienia" enctype="multipart/form-data" class="mainForm" action="" method="post">
				<div class="formRow">
					Wpisz parametry oddzielając je średnikiem np. 120;140;160;180
				</div>
		<h2 class="section">Wyszukiwarka mieszkań</h2>
				<div class="formRow">
					<label for="mieszkania_pokoje">Pokoje</label>
					<div class="formRight tip rowInfo"><input type="text" name="mieszkania_pokoje" id="mieszkania_pokoje" value="<?=$this->header->mieszkania_pokoje;?>" size="77" /></div>
				</div>
				<div class="formRow">
					<label for="mieszkania_metry">Metraż</label>
					<div class="formRight tip rowInfo"><input type="text" name="mieszkania_metry" id="mieszkania_metry" value="<?=$this->header->mieszkania_metry;?>" size="77" /></div>
				</div>
				<div class="formSubmit"><input type="submit" name="submitSearch" id="submit" value="Zapisz" class="greyishBtn" /></div>
			</form>
		</div>
		</div>
	</div>
</div>