<!doctype html>
<html lang="pl">
<head>
	<meta charset="utf-8">
	<title>kCMS - Logowanie</title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Jacek Kurowski">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no">
	<meta name="robots" content="noindex, nofollow">

	<!-- Style -->
    <link rel="stylesheet" href="<?=$this->baseUrl;?>/public/styles/cms/admin.css?v=1">

	<!-- jQuery -->
    <script src="<?=$this->baseUrl; ?>/public/js/jquery.js" charset="utf-8"></script>
	<script src="<?=$this->baseUrl; ?>/public/js/validation.js" charset="utf-8"></script>
	<script src="<?=$this->baseUrl; ?>/public/js/pl.js" charset="utf-8"></script>
    <script src="<?=$this->baseUrl; ?>/public/js/cms.js" charset="utf-8"></script>

	</head>
	<body id="logowanie">
		<?=$this->layout()->content; ?>
	</body>
</html>