<div class="title"><h1><?=$this->controlname;?></h1></div>
<div class="row-fluid">
	<div class="span12">
		<div class="widget">
			<div class="table-header"><form action="" id="filter-form">
			<label>
			<span>Szukaj:</span><input type="text" size="30" maxlength="30" value="" id="filter" name="filter" />
			</label>
			</form></div>
			<table width="100%" cellspacing="0" cellpadding="0" class="adm" id="sortable">
				<thead>
					<tr>
						<th width="50%">Nazwa</th>
						<th width="5%">Pozycja</th>
						<th width="10%">Typ</th>
						<th width="5%">Status</th>
						<th width="20%">Data modyfikacji</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody class="content">
					<?php $menu = new kCMS_MenuBuilder(); echo $menu->get_adminmenu_html(); ?>
				</tbody>
			</table>
			<div class="table-footer">
				<a href="<?=$this->baseUrl;?>/admin/strony/nowa-strona/" class="button greyishBtn">Dodaj stronę</a>
				<a href="<?=$this->baseUrl;?>/admin/strony/nowy-link/" class="button greyishBtn">Dodaj link</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" language="javascript">
//<![CDATA[
$(document).ready(function(){
	$("#sortable tbody.content").sortuj('<?php echo $this->baseUrl;?>/admin/strony/ustaw/');
});
//]]>
</script>