<form method="post" action="" class="validateform">
	<div class="row">
		<div class="col-12">
			<h2 class="source after-title">Skontaktuj się z nami</h2>
			<p class="section-title after-h2">Z przyjemnością odpowiemy na wszystkie Twoje pytania</p>
		</div>
	</div>
	<div class="form-row row">
		<div class="col-3">
			<div class="inputs">
				<div class="input">
					<label for="form_imie">Imię</label>
					<input name="form_imie" id="form_imie" class="validate[required]" placeholder="Imię" type="text">
				</div>
				<div class="input">
					<label for="form_email">E-mail</label>
					<input name="form_email" id="form_email" class="validate[required,custom[email]]" placeholder="E-mail" type="email">
				</div>
				<div class="input">
					<label for="form_tel">Telefon</label>
					<input name="form_tel" id="form_tel" class="validate[custom[phone]]" placeholder="Telefon" type="tel">
				</div>
			</div>
		</div>
		<div class="col-9">
			<div class="input">
				<label for="form_wiadomosc">Treść wiadmości</label>
				<textarea name="form_wiadomosc" id="form_wiadomosc" placeholder="Treść wiadomości"></textarea>
			</div>
		</div>
	</div>
	<div class="form-row row">
		<div class="col-12 obowiazek">
			<?=$this->rodo->obowiazek;?>
		</div>
	</div>
	<div class="form-row row">
		<div class="col-12 rules">
		<?php foreach($this->regulki as $regulka){?>
			<label for="zgoda_<?=$regulka->id;?>" class="rules-text"><input name="zgoda_<?=$regulka->id;?>" id="zgoda_<?=$regulka->id;?>" value="1" type="checkbox" <?php if($regulka->wymagane == 1){;?>class="validate[required]"<?php } ?> data-prompt-position="topLeft:0"><p><?=$regulka->tresc;?></p></label>
			<div class="clr"></div>
		<?php } ?>
		</div>
	</div>
	<div class="form-row row">
		<div class="col-6">
			<ul class="formicons list-unstyled mb-0">
				<li class="formicons-address">
                    <p><b>GOLDEN ESTATE DEVELOPMENT</b></p>
                    <p>ul. Betonowa 2/1</p>
                    <p>00-000 Miasto</p>
				</li>
				<li class="formicons-contact">
					<p>tel. 000 000 000</p>
					<p>sprzedaz@....</p>
					<p>biuro@....</p>
				</li>
			</ul>
		</div>
		<div class="col-6">
			<div class="input text-right">
				<script type="text/javascript">
					document.write("<button class=\"bttn bttn-send\" type=\"submit\">WYŚLIJ</button>");
				</script>
				<noscript><p><b>Do poprawnego działania, Java musi być włączona.</b><p></noscript>
			</div>
		</div>
	</div>
</form>