<footer>
	<div id="footer">
		<div class="fluid-container">
			<div class="row">
				<div class="col-12">
					<div class="border-top"></div>
				</div>
			</div>
			<div class="row">
				<div class="col-6">
					<a href="#" target="_blank"><img src="<?=$this->baseUrl;?>/public/gfx/template/liph.png" alt="Łódzka Izba Przymysłowo-Handlowa"></a> <a href="#" target="_blank"><img src="<?=$this->baseUrl;?>/public/gfx/template/pzfd.png" alt="Polski Związek Firm Deweloperskich"></a> <a href="#" target="_blank"><img src="<?=$this->baseUrl;?>/public/gfx/template/rzetelnafirma.png" alt="Rzetelna firma"></a>
				</div>
				<div class="col-6 text-right"><a href="https://golden-lion.pl/">GOLDEN ESTATE DEVELOPMENT 2018</a><br><a href="#" title="" target="_blank">JK Design</a></div>
			</div>
			<div class="row">
				<div class="col-12 stopka text-center">
					<?=$this->header->stopka;?>
				</div>
			</div>
		</div>
	</div>
</footer>